### ISSUE TITLE
Checklists with subitems display poorly

### ISSUE THREAD

**Issue by rickymccallum87** [kinoute/typora-github-night-theme#1]
My primary use case for Typora is checking off to-do items. Love this theme. Thanks for taking a look.

![checklist](https://user-images.githubusercontent.com/29452509/105204524-4465e700-5b12-11eb-9192-85b1abc39658.png)

**Comment by kinoute** [comment]
Thanks for reporting it! It seems the checkboxes get the same style as normal nested lists. I will fix this right now

**Comment by kinoute** [comment]
@rickymccallum87 I just pushed a fix, can you confirm it's working now?

https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.2.3

**Comment by rickymccallum87** [comment]
Looks good now. Thank you! 😄
