### ISSUE TITLE
Numbered list numbers grow in size

### ISSUE THREAD

**Issue by lebigot** [kinoute/typora-github-night-theme#10]
Thank you for this nice theme.

Now (on macOS at least), subsequent numbered list numbers (the "1." below) _grow_ in font size, for a source like the following:
```
1. Lkjmlkj 
   1. lkjmlkj
      1. lkjmklj
         1. lkjmlkj
            1. lkjmklj
               1. lmkjmlj
```
The resulting effect is strange and, I guess, not intended.

I would expect each number to be of the same size as the text.

**Comment by kinoute** [comment]
Hi, thanks for the report.

I'm unable to reproduce the bug: the list numbers have the same font size:

![Capture d’écran 2021-05-14 à 12 16 11](https://user-images.githubusercontent.com/623763/118256831-34518900-b4ae-11eb-8b09-670b688a65a4.png)

Could you provide a screenshot and a markdown file to show me the problem?

I agree that the font size should be a little higher to match the text's one though.

**Comment by lebigot** [comment]
The markdown in the original post is enough to show the problem.

Here is the corresponding screenshot, in Typora 0.10.10 (5354):
<img width="512" alt="Screen Shot 2021-05-17 at 12 01 54" src="https://user-images.githubusercontent.com/5793/118471260-d9b36980-b707-11eb-959f-ea23c7a9954b.png">

**Comment by kinoute** [comment]
Using Version 0.10.10 (5354) on macOS Mojave 10.14.6, I can't find a way to reproduce the bug. If Typora is doing this randomly, it is either a bug on their side, either maybe an indentation problem of your list?

When it happens, you could enable the debug mode in the "help" menu, right click somewhere on your text, "inspect element", and check the CSS styles of the wrong list numbers. That could lead, if it's the reason, to the CSS rules responsible of this, and I could fix them.

**Comment by lebigot** [comment]
Thanks for following up.

I'm not sure if I was looking at the right thing, but maybe the following is relevant?
```
<ol class="ol-list" start="" cid="n18" mdtype="list"><li class="md-list-item md-focus-container" cid="n19" mdtype="list_item"><p cid="n20" mdtype="paragraph" contenteditable="true" class="md-end-block md-p md-focus"><span md-inline="plain" class="md-plain md-expand">lmkjmlj</span></p></li></ol>
```
If not, maybe you can tell me what I should be looking for?

**Comment by kinoute** [comment]
@lebigot I am interested in the CSS values for this HTML code indeed. You can see them here, on the right tab:

![Capture d’écran 2021-05-17 à 23 41 00](https://user-images.githubusercontent.com/623763/118560187-5fb3cc80-b769-11eb-8b28-bd7e44849180.png)

Be sure you select an `ol` element on the left. Select a nested one, i.e a list number that is bigger than normal. 

By the way, I don't know if you downloaded the theme from the releases page but two days ago I fixed something and pushed it to master. I didn't make a release for it yet so could you also try to download again the theme from master and tell me if it changes something?

**Comment by lebigot** [comment]
Thanks.

I downloaded the current master. So far I haven't observed the problem, but again it disappears randomly, sometimes, so we'll see.

I'll report here.

**Comment by lebigot** [comment]
I haven't seen the problem in a while, with Typora Beta 0.10.10, so I'm closing this issue. Thanks for your feedback!
