### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by Lraxer** [kinoute/typora-github-night-theme#12]
I'm using Typora (version 0.10.11) and github night theme (version 0.5.0) in Windows 10.
I want to use custom fonts, so I followed the [instruction](https://support.typora.io/Custom-Font/), creating `base.user.css` under theme folder and appending these lines in it:
```css
body {
  font-family: Consolas, "思源宋体";
}
```
It worked in themes such as [Github theme](https://theme.typora.io/theme/Github/), you can see the difference.
Before using `base.user.css`:

![typora-github-theme-before](https://user-images.githubusercontent.com/32860114/124146918-cfcfa500-dac0-11eb-969b-95c6ed31abe5.png)

After using `base.user.css`:
![typora-github-theme-after](https://user-images.githubusercontent.com/32860114/124147039-ee35a080-dac0-11eb-9269-83dc82e170bd.png)

But in github night theme, `base.user.css` can not work.
Before:
![typora-github-night-theme-before](https://user-images.githubusercontent.com/32860114/124147415-3fde2b00-dac1-11eb-833c-96edbd0042b5.png)

After:
![typora-github-night-theme-after](https://user-images.githubusercontent.com/32860114/124147432-440a4880-dac1-11eb-967d-6d97b53a0792.png)

I'm sorry that I know little about css, I just tried to remove `思源宋体` in `base.user.css` but nothing changed.
```css
body {
  font-family: Consolas;
}
```
I also tried `{current-theme}.user.css`, which didn't work either. 
Is there any way to solve this problem? Thank you!

**Comment by kinoute** [comment]
Hello,

I'm not familiar with the `xxx.user.css` system to override fonts. I will look at it!

In the meantime, you could try to edit the `github-night.css` file directly.  We use "Nunito" as our main font. To change that to Consolas, you can edit every line that looks like this:

```css
    font-family: "Nunito", sans-serif;
```

to 

```css
    font-family: "Consolas", sans-serif;
```

Example:

https://github.com/kinoute/typora-github-night-theme/blob/161ca5f3211adf0584e553e8822ff14241f420f9/github-night.css#L154-L158

etc.

I just did it for you here: https://gist.github.com/kinoute/238cc57dbc4929faeb6f3e204a48e336

Replace the content of the `github-night.css` file by the one in the link.

Yann

**Comment by Lraxer** [comment]
Thanks for your help! It would be nice if github-night supported `xxx.user.css`.
