### ISSUE TITLE
The task list is not aligned horizontally

### ISSUE THREAD

**Issue by Tian90coder** [kinoute/typora-github-night-theme#15]
I see that the task list is not aligned horizontally. Can this be fixed in the next release?
<img width="275" alt="截屏2021-08-15 下午2 57 54" src="https://user-images.githubusercontent.com/56345542/129469980-284a6cec-4478-4723-bdb3-f58b603db506.png">

**Comment by Tian90coder** [comment]
Or could you indicate where refactor in the code would fix the bug🤔

**Comment by kinoute** [comment]
I will fix it today

**Comment by kinoute** [comment]
Fixed in new release: https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.6.1
