### ISSUE TITLE
Spacing inside inline code-block is wrong

### ISSUE THREAD

**Issue by relikd** [kinoute/typora-github-night-theme#17]
The screenshot says everything. The space between “swift” an “main.swift” is just a single, normal, space. But the preview displays it as if it is a tab or multiple spaces.

![screen](https://user-images.githubusercontent.com/1321720/138487495-7806743b-3adf-48ac-a37b-f3d37082693f.png)

**Comment by kinoute** [comment]
@relikd I pushed a fix to the master branch. Please download/reinstall the theme to confirm it works before I can create a new release.

**Comment by relikd** [comment]
works perfectly, thanks (y)
