### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Laeeb** [kinoute/typora-github-night-theme#19]
Click to download prompt not found.

**Comment by kinoute** [comment]
Hello, can you give me more details please?

The theme can be downloaded here: https://github.com/kinoute/typora-github-night-theme/releases

**Comment by Laeeb** [comment]
![image](https://user-images.githubusercontent.com/90699180/171850470-1d58d5fc-cc5a-45c0-8ec8-083fb79e545d.png)
![image](https://user-images.githubusercontent.com/90699180/171850916-0374fd7e-9913-422d-b0d1-906b4764aa61.png)

When  I  click  on  download  Sourcecode(zip), the  jump  shows  Not Found.     As shown in the picture.

**Comment by kinoute** [comment]
When I go to my link posted above, the "Source code (zip)" link is different than the one you have on your screenshot:

https://github.com/kinoute/typora-github-night-theme/archive/refs/tags/v0.6.2.zip

**Comment by Laeeb** [comment]
> When I go to my link posted above, the "Source code (zip)" link is different than the one you have on your screenshot:
> 
> https://github.com/kinoute/typora-github-night-theme/archive/refs/tags/v0.6.2.zip

Oh my problem is solved, my friend can access the download. I guess I thought I had a gas pedal or port problem. Thanks a lot! Great theme!
