### ISSUE TITLE
Found some style issues

### ISSUE THREAD

**Issue by y761350477** [kinoute/typora-github-night-theme#2]
## FAQ
Hello, I really like the dark theme you made.
But I used it on the windows platform and found some problems:
1. ``` is displayed as a `.

## Typora default GitHub Theme

a ` display:
![](https://y76.oss-cn-beijing.aliyuncs.com/20210121185901.png)

three ` display:
![](https://y76.oss-cn-beijing.aliyuncs.com/20210121185959.png)

## GitHub Night Theme
a ` display:
![](https://y76.oss-cn-beijing.aliyuncs.com/20210121185517_%E9%94%99%E4%BD%8D.png)

three ` display:
![](https://y76.oss-cn-beijing.aliyuncs.com/20210121185600.png)

**Comment by kinoute** [comment]
Hello,

Thanks for reporting this. I have this problem on the other theme I made. Could you tell me what options you have here?

![Capture d’écran 2021-01-21 à 12 17 31](https://user-images.githubusercontent.com/623763/105344008-aaba3a80-5be2-11eb-8021-c1ad2e0d7186.png)

**Comment by kinoute** [comment]
@y761350477 I pushed a potential fix for this issue to master, could you download the theme again? Here is the link to download master:

https://github.com/kinoute/typora-github-night-theme/archive/master.zip

**Comment by y761350477** [comment]
> @y761350477 I pushed a potential fix for this issue to master, could you download the theme again? Here is the link to download master:
> 
> https://github.com/kinoute/typora-github-night-theme/archive/master.zip

thanks!
nice!
