### ISSUE TITLE
Scroll bar cannot be seen

### ISSUE THREAD

**Issue by tml104** [kinoute/typora-github-night-theme#3]
In this theme scroll bar cannot be shown:
![20210130210726](https://user-images.githubusercontent.com/46257287/106357155-50864b80-633f-11eb-97fa-d7c523f5faf9.png)

Instead Official GitHub Theme looks like this, which can show it correctly:
![20210130210752](https://user-images.githubusercontent.com/46257287/106357152-46fce380-633f-11eb-9311-9930174bb33a.png)

**Comment by kinoute** [comment]
Hi,

This was done on purpose as I couldn't find a nice way to incorporate the scroll bars in the theme, so I removed them just like on macOS. But I understand that for some people it might be useful so I'm going to think again about how to add them nicely to fit with the theme!

Regards

**Comment by Tian90coder** [comment]
Can you add a scroll bar to deal with a large number of text content files, even if it may not be beautiful, but useful

**Comment by kinoute** [comment]
@Tian90coder I will look at it!

**Comment by kinoute** [comment]
@Tian90coder @tml104 I added a scrollbar to the document on the right, tell me if it's working for you: https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.4.0

**Comment by tml104** [comment]
> @Tian90coder @tml104 I added a scrollbar to the document on the right, tell me if it's working for you: https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.4.0

It is of great usefulness for me, thanks, I like it!

**Comment by Tian90coder** [comment]
> @Tian90coder I will look at it!

It's cool. I'm in love with it
