### ISSUE TITLE
代码超过一千行，行号样式错误

### ISSUE THREAD

**Issue by WangJincheng4869** [kinoute/typora-github-night-theme#7]
如图所示：
![image](https://user-images.githubusercontent.com/41162158/111603975-d25b0700-880f-11eb-9bc1-5e13e0c5e3d7.png)

**Comment by kinoute** [comment]
Hello,

Thanks for the report! Could you send me a markdown file to reproduce the issue?

**Comment by WangJincheng4869** [comment]
> Hello,
> 
> Thanks for the report! Could you send me a markdown file to reproduce the issue?
文件下载地址
[https://www.jcwang4869.top/version-1.10.md](version-1.10.md)

**Comment by kinoute** [comment]
Thank you! I'm working on a fix

**Comment by kinoute** [comment]
@WangJincheng4869 I just pushed a fix, tell me if it's working for you: https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.4.0

**Comment by WangJincheng4869** [comment]
> @WangJincheng4869 I just pushed a fix, tell me if it's working for you: https://github.com/kinoute/typora-github-night-theme/releases/tag/v0.4.0

已经修复，非常感谢！
![image](https://user-images.githubusercontent.com/41162158/111719098-24df0680-8896-11eb-9a22-8aef072cdbe3.png)
