### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by liurunsmileliu** [kinoute/typora-github-night-theme#8]
Can you tell me how to modify the background color of the selected text?
Thanks！
![image](https://user-images.githubusercontent.com/80946535/111748751-e06e5d80-88cb-11eb-8843-fdb588058013.png)

**Comment by kinoute** [comment]
Hello,

That's weird. The background of the selected text should be:

![Capture d’écran 2021-03-19 à 09 17 15](https://user-images.githubusercontent.com/623763/111750845-0972fc00-8894-11eb-8751-2a60e9ceecc0.png)

It seems it doesn't work as intended on Windows. I have to look at it. If you want to change the colour manually, you can try to edit the `github-night.css` and change the value of the `--select-text-bg-color` CSS variable

**Comment by liurunsmileliu** [comment]
This method is feasible 
Thanks

Lrunzhi

发件人: Yann Defretin
发送时间: 2021年3月19日 16:22
收件人: kinoute/typora-github-night-theme
抄送: liurunsmileliu; Author
主题: Re: [kinoute/typora-github-night-theme] Hello (#8)

Hello,
That's weird. The background of the selected text should be:

It seems it doesn't work as intended on Windows. I have to look at it. If you want to change the colour manually, you can try to edit the github-night.css and change the value of the --select-text-bg-color CSS variable

**Comment by kinoute** [comment]
@liurunsmileliu I fixed the color on Win/Linux, please try again by downloading the master: https://github.com/kinoute/typora-github-night-theme/archive/master.zip
